version: "3.8"
# services / containers
services:
  # express app
  web-ukhuwahproject:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web-ukhuwahproject
    image: web-ukhuwahproject:1.0.4
    restart: always
    ports:
      - 3000:3000
    environment:
      NUXT_PUBLIC_API_URI: https://api.ukhuwahproject.com
